// AUTOGENERATED by `pnpm codegen`. Do not edit; your changes will be overwritten.

export type Me = { id: string; email: string; role?: string };

export interface ApiClient {
  getMe(): Promise<Me | null>;
}
